# API로 데이터 수집

In [ ]:
####### 10/23 부터 2020년까지 수집 ##### (202001010000 - 202212312359)
# --------------------------------------------- #
######## 페이지네이션 적용 코드 ##############

import requests
import os
from datetime import datetime

# API URL 및 쿼리 파라미터
url = "https://gnip-api.twitter.com/search/fullarchive/accounts/ArsPraxia/prod.json"
keyword = 'Samsung'  ######## 원하는 키워드로 수정 필요
minus_keyword = ''

###### !!확인 필!! >>> minus_keyword가 잘 들어갔는지 확인 <<< ######
params = {
    "query": (keyword) + " " + (minus_keyword) + " lang:id -is:retweet -is:nullcast -has:links",
    "maxResults": 500,
    "fromDate" : '202001010000',
    "toDate" : '202212312359'
}

# 현재 날짜를 YYYYMMDD 형식의 문자열로 변환
current_date = datetime.now().strftime('%Y%m%d')

# 사용자 인증 정보
auth = ("#####", "#####")



# 폴더 이름 지정
folder_name = f'원시데이터/{current_date}_data/{keyword}'
# folder_name = '날짜테스트'

# 폴더가 없다면 생성
if not os.path.exists(folder_name):
    os.makedirs(folder_name)



# 페이지 번호 초기화
page_number = 1

# 첫 번째 페이지 요청
response = requests.get(url, params=params, auth=auth)

# 응답 확인 및 데이터 저장
while response.status_code == 200:
    # 파일 경로 생성
    file_path = os.path.join(folder_name, f"{current_date}_twitter_{keyword}_{page_number}.json")
    
    # JSON 데이터 저장
    with open(file_path, "w", encoding="utf-8") as file:
        file.write(response.text)
    
    # 응답 JSON 데이터 로드
    response_data = response.json()
    
    # 'next' 키가 있는지 확인하고, 있다면 다음 페이지 데이터 요청
    next_token = response_data.get('next', None)
    if next_token is not None:
        params['next'] = next_token
        response = requests.get(url, params=params, auth=auth)
        page_number += 1  # 페이지 번호 증가
    else:  # 'next' 키가 없다면 루프 종료
        break
else:
    print(f"Error: Unable to fetch data. Status code: {response.status_code}")

OSError: [Errno 28] No space left on device

In [36]:

######## 페이지네이션 적용 코드 ##############

import requests
import os
from datetime import datetime

# API URL 및 쿼리 파라미터
url = "https://gnip-api.twitter.com/search/fullarchive/accounts/ArsPraxia/prod.json"
keyword = 'Joseon'  ######## 원하는 키워드로 수정 필요
minus_keyword = '-Samsung -Korea -Seoul -Incheon -BTS -"Squid Game" -KBS -Hallyu -Lesserafim -Choi -Seo -KBS -Naver -Korean -IVE -Hangul -tvN -Dookki -Seventeen -Innisfree -Yoon -Hongdae -Busan -Hyundai -Sejong -Gyeongbokgung -"newjenas" -HYBE -JTBC -Itaewon -Hyuk -TWICE -"Stray Kids" -Aespa -ITZY -Eun -Hwang -Gangnam -ATEEZ -Myeongdong -tteokbokki -Jeju -Hyun -Bulgogi -Blackpink -CLIO -Skinfood -Jung -AKMU -Bongsoon -NCT127 -Hyo -Asiana -Kartrider -PUBG -Hanhwa -BTOB -Kimchi -Seok -kdrama -NMIXX -Lotte -kpop -Binggrae -Shinsegae -Mabinogi -Doosan -"Hotel Del Luna" -Suzy -Kep1er -Joseon'

###### !!확인 필!! >>> minus_keyword가 잘 들어갔는지 확인 <<< ######
params = {
    "query": (keyword) + " " + (minus_keyword) + " lang:id -is:retweet -is:nullcast -has:links",
    "maxResults": 500,
    "fromDate" : '202301010000',
    "toDate" : '202309302359'
}

# 현재 날짜를 YYYYMMDD 형식의 문자열로 변환
current_date = datetime.now().strftime('%Y%m%d')

# 사용자 인증 정보
auth = ("minwoo@arspraxia.com", "treum8864!")



# 폴더 이름 지정
folder_name = f'원시데이터/{current_date}_data/{keyword}'
# folder_name = '날짜테스트'

# 폴더가 없다면 생성
if not os.path.exists(folder_name):
    os.makedirs(folder_name)



# 페이지 번호 초기화
page_number = 1

# 첫 번째 페이지 요청
response = requests.get(url, params=params, auth=auth)

# 응답 확인 및 데이터 저장
while response.status_code == 200:
    # 파일 경로 생성
    file_path = os.path.join(folder_name, f"{current_date}_twitter_{keyword}_{page_number}.json")
    
    # JSON 데이터 저장
    with open(file_path, "w", encoding="utf-8") as file:
        file.write(response.text)
    
    # 응답 JSON 데이터 로드
    response_data = response.json()
    
    # 'next' 키가 있는지 확인하고, 있다면 다음 페이지 데이터 요청
    next_token = response_data.get('next', None)
    if next_token is not None:
        params['next'] = next_token
        response = requests.get(url, params=params, auth=auth)
        page_number += 1  # 페이지 번호 증가
    else:  # 'next' 키가 없다면 루프 종료
        break
else:
    print(f"Error: Unable to fetch data. Status code: {response.status_code}")

In [21]:

######## 페이지네이션 적용 코드 ##############
######## 띄어쓰기 용 코드 ###########

import requests
import os
from datetime import datetime

# API URL 및 쿼리 파라미터
url = "https://gnip-api.twitter.com/search/fullarchive/accounts/ArsPraxia/prod.json"
original_keyword = '"Hotel Del Luna"'  ######## 원하는 키워드로 수정 필요
keyword = original_keyword.replace('"', '')
minus_keyword = '-Samsung -Korea -Seoul -Incheon -BTS -"Squid Game" -KBS -Hallyu -Lesserafim -Choi -Seo -KBS -Naver -Korean -IVE -Hangul -tvN -Dookki -Seventeen -Innisfree -Yoon -Hongdae -Busan -Hyundai -Sejong -Gyeongbokgung -"newjenas" -HYBE -JTBC -Itaewon -Hyuk -TWICE -"Stray Kids" -Aespa -ITZY -Eun -Hwang -Gangnam -ATEEZ -Myeongdong -tteokbokki -Jeju -Hyun -Bulgogi -Blackpink -CLIO -Skinfood -Jung -AKMU -Bongsoon -NCT127 -Hyo -Asiana -Kartrider -PUBG -Hanhwa -BTOB -Kimchi -Seok -kdrama -NMIXX -Lotte -kpop -Binggrae -Shinsegae -Mabinogi -Doosan'

###### !!확인 필!! >>> minus_keyword가 잘 들어갔는지 확인 <<< ######
params = {
    "query": (original_keyword) + " " + (minus_keyword) + " lang:id -is:retweet -is:nullcast -has:links",
    "maxResults": 500,
    "fromDate" : '202301010000',
    "toDate" : '202309302359'
}

# 현재 날짜를 YYYYMMDD 형식의 문자열로 변환
current_date = datetime.now().strftime('%Y%m%d')

# 사용자 인증 정보
auth = ("minwoo@arspraxia.com", "treum8864!")



# 폴더 이름 지정
folder_name = f'원시데이터/{current_date}_data/{keyword}'
# folder_name = '날짜테스트'

# 폴더가 없다면 생성
if not os.path.exists(folder_name):
    os.makedirs(folder_name)



# 페이지 번호 초기화
page_number = 1

# 첫 번째 페이지 요청
response = requests.get(url, params=params, auth=auth)

# 응답 확인 및 데이터 저장
while response.status_code == 200:
    # 파일 경로 생성
    file_path = os.path.join(folder_name, f"{current_date}_twitter_{keyword}_{page_number}.json")
    
    # JSON 데이터 저장
    with open(file_path, "w", encoding="utf-8") as file:
        file.write(response.text)
    
    # 응답 JSON 데이터 로드
    response_data = response.json()
    
    # 'next' 키가 있는지 확인하고, 있다면 다음 페이지 데이터 요청
    next_token = response_data.get('next', None)
    if next_token is not None:
        params['next'] = next_token
        response = requests.get(url, params=params, auth=auth)
        page_number += 1  # 페이지 번호 증가
    else:  # 'next' 키가 없다면 루프 종료
        break
else:
    print(f"Error: Unable to fetch data. Status code: {response.status_code}")

<br>
<br>
<br>

# CSV 만들기

In [37]:
from datetime import datetime


def to_date(date_str):
    # 문자열을 datetime 객체로 변환
    date_obj = datetime.strptime(date_str, "%a %b %d %H:%M:%S +0000 %Y")

    # datetime 객체를 원하는 형식의 문자열로 변환
    formatted_date_str = date_obj.strftime("%Y-%m-%d")

    return formatted_date_str

In [38]:
############# Version 3 ##################
######## 원하는 형태로 만드는 코드 ############
######## 키워드_assemble로 저장되는 코드 ##############

import pandas as pd
import json
import os
from datetime import datetime

# 모든 JSON 파일을 불러오기 위해 폴더 지정
folder_name = f'원시데이터/{current_date}_data/{keyword}'

# 최종 데이터를 저장할 딕셔너리 초기화
final_data = []


# 폴더 내의 모든 JSON 파일 처리
for file_name in os.listdir(folder_name):

    if file_name.endswith('.json'):
        file_path = os.path.join(folder_name, file_name)
        
        # 파일 읽기
        with open(file_path, 'r', encoding='utf-8') as file:
            json_data = json.load(file)
        date = file_name.split('_')[0]
        source = file_name.split('_')[1]
        keyword=file_name.split('_')[2]
        # 각 결과에 대해 원하는 데이터 추출

    
        for result in json_data['results']:
            # extended_tweet의 full_text 값이 있으면 사용, 없으면 text 값을 사용
            text = result.get('extended_tweet', {}).get('full_text', result['text'])
            created_at = str(result['created_at'])
            

            # 최종 데이터에 추가
            final_data.append({
                'created_at': created_at,
                'Text': text,
                'Filename' :"C:/Users/USER/Desktop/" + file_path,     #"C:/Users/USER/Desktop/트위터데이터/" 가 나으려나
            })

    
keyword = file_name.replace('.json', '').split('_')[2]
df= pd.DataFrame(final_data)
df['Pub_Subj']= keyword
df['Col_Date']=  datetime.now().strftime('%Y-%m-%d')
df['Title']= 'Twitter_'+keyword
df['Doc_ID'] = date + '_' + source + '_' + keyword + df.index.map(lambda x: f"{x + 1:06}")

# 문서 ID, 수집일, 수집 키워드 표기
df['Pub_Date']=df['created_at'].apply(to_date)
df.drop('created_at', axis=1, inplace=True)

df.tail(10)

,Text,Filename,Pub_Subj,Col_Date,Title,Doc_ID,Pub_Date
3822,5. Ternyata rumah ini luas walaupun rasanya ka...,C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon003823,2023-01-02
3823,"@cappucinoturu @yeonanist Ayang kan seruuu, ad...",C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon003824,2023-01-02
3824,serum beauty of joseon bagus bgt anjay,C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon003825,2023-01-02
3825,"@leonjwiniee 3 serangkainya cwok semua, kyknya...",C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon003826,2023-01-02
3826,"@xeesoxcee WKWKWKWK gapapa un, nanti aku buka ...",C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon003827,2023-01-02
3827,@AntalaAU “Sekongkol sama iblis dineraka biar ...,C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon003828,2023-01-02
3828,Cause kisah mereka tuh ibaratnya Jang Uk dari ...,C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon003829,2023-01-01
3829,@bumbucimoul AOWKAOWKWOK KOKOPPPPP. tu drama m...,C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon003830,2023-01-01
3830,@rdwt8 Sedih banget joseon era 😭,C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon003831,2023-01-01
3831,"Masih awal tahun, mimpi gw udah ngadi2. Masa g...",C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon003832,2023-01-01

<br>
<br>
<br>

# 텍스트 정제

In [39]:
import re

def clean_text(text):
    # 이모티콘 제거
    emoji_pattern = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F700-\U0001F77F"  # alchemical symbols
                               u"\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
                               u"\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
                               u"\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
                               u"\U0001FA00-\U0001FA6F"  # Chess Symbols
                               u"\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
                               u"\U00002702-\U000027B0"  # Dingbats
                               u"\U000024C2-\U0001F251" 
                               "]+", flags=re.UNICODE)
    text = emoji_pattern.sub(r'', text)
    
    # 멘션 제거
    mention_pattern = re.compile(r'@\S+')
    text = mention_pattern.sub(r'', text)
    
    # "@" 문자만 제거
    text = text.replace('@', '')
    
    # URL 제거
    url_pattern = re.compile(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+')
    text = url_pattern.sub(r'', text)

    # HTML Entities 제거
    html_entity_pattern = re.compile(r'&[a-zA-Z]+;')
    text = html_entity_pattern.sub(r'', text)
    
    # 특수문자 제거
    special_char_pattern = re.compile(r'[\^_\+\/,\(\):*]')
    text = special_char_pattern.sub('', text)
    # 한글 제거
    korean_char_pattern = re.compile(r'[가-힣]+')
    text = korean_char_pattern.sub(r'', text)
    
    # "(cont.)" 제거
    cont_pattern = re.compile(r'\(cont\.\)\s*|\s*\(cont\.\)')
    text = cont_pattern.sub(r'', text)

    # 줄바꿈 제거
    text = text.replace('\n', ' ')

    # "fvck", "fuck", "porn", "pukimak", "sial", "sialan", "bajingan" 제거
    explicit_words_pattern = re.compile(r'fvck|fuck|porn|pukimak|sial|sialan|bajingan', flags=re.IGNORECASE)
    text = explicit_words_pattern.sub('', text)
    
    # "["와 "]" 특수 문자 제거
    text = text.replace('[', '').replace(']', '')

    # 연속된 "#" 기호를 공백으로 대체
    text = re.sub(r'#\s+#', ' ', text)
    
    # "#" 기호 제거
    text = text.replace('#', '')
    
    return text



df['Text']=df['Text'].apply(clean_text)


# 'Text' 컬럼 중심으로 중복 제거
df.drop_duplicates(subset='Text', inplace=True)
df.reset_index(drop=True, inplace=True)

df.head(10)

,Text,Filename,Pub_Subj,Col_Date,Title,Doc_ID,Pub_Date
0,Korsel itu seniat itu ya bikin drakor tema his...,C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon000001,2023-09-30
1,Beauty of Joseon anjir war kayak gmn tuh,C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon000002,2023-09-30
2,Cinderella era joseon yah ini,C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon000003,2023-09-30
3,Ayo ngobrol serius sebutkan urutan raja di Di...,C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon000004,2023-09-30
4,aku habis belanja skincare. terus aku takut co...,C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon000005,2023-09-30
5,Sageuk bun tapi keknya sageuk lawak ttg mak c...,C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon000006,2023-09-30
6,Song of Bandits angkat tema yg gue suka deh jo...,C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon000007,2023-09-30
7,geram eh dengan Raja Joseon lembik dan lambat...,C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon000008,2023-09-30
8,Cheong ha cegil joseon anjir,C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon000009,2023-09-30
9,Di belakang kerajaan joseon bil,C:/Users/USER/Desktop/원시데이터/20231023_data/Jose...,Joseon,2023-10-23,Twitter_Joseon,20231023_twitter_Joseon000010,2023-09-30

In [40]:
import os
from datetime import datetime

# 원하는 폴더 구조 생성
folder_path = os.path.join("원시데이터_csv", current_date)

# 폴더가 없다면 생성
if not os.path.exists(folder_path):
    os.makedirs(folder_path)



df.to_csv(f"./원시데이터_csv/{current_date}/{current_date}_twitter_{keyword}.csv", encoding='utf-8-sig', index=False)